import os
import json
import subprocess
import sys

def load_cookies(cookie_file):
    """Load cookies dari file JSON (format Cookie Editor extension)"""
    try:
        with open(cookie_file, 'r') as f:
            cookies_list = json.load(f)
        
        # Konversi dari format Cookie Editor ke dictionary
        cookies = {}
        if isinstance(cookies_list, list):
            for cookie in cookies_list:
                if 'name' in cookie and 'value' in cookie:
                    cookies[cookie['name']] = cookie['value']
        
        # Cek apakah cookies penting ada
        if 'sp_dc' in cookies and 'sp_key' in cookies:
            print(f"✓ Cookies Spotify berhasil dimuat ({len(cookies)} cookies)")
            return cookies
        else:
            print("⚠ Cookies tidak lengkap (sp_dc atau sp_key tidak ditemukan)")
            return cookies
            
    except FileNotFoundError:
        print(f"✗ File {cookie_file} tidak ditemukan!")
        return None
    except json.JSONDecodeError:
        print("✗ Format cookies tidak valid!")
        return None

def create_cookies_txt(cookies_dict, output_file="cookies.txt"):
    """Konversi cookies JSON ke format Netscape untuk yt-dlp"""
    with open(output_file, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by script\n\n")
        
        # Format: domain, flag, path, secure, expiration, name, value
        for name, value in cookies_dict.items():
            f.write(f".spotify.com\tTRUE\t/\tTRUE\t0\t{name}\t{value}\n")
    
    return output_file

def check_spotdl_installed():
    """Check apakah spotdl sudah terinstall"""
    try:
        # Coba import module dulu
        import spotdl
        print(f"✓ spotdl versi {spotdl.__version__} terdeteksi")
        return True
    except ImportError:
        # Jika import gagal, coba cek via command line
        try:
            result = subprocess.run(['spotdl', '--version'], 
                                  capture_output=True, 
                                  text=True, 
                                  timeout=5)
            if result.returncode == 0:
                print(f"✓ spotdl terdeteksi: {result.stdout.strip()}")
                return True
        except:
            pass
        
        # Coba dengan python -m spotdl
        try:
            result = subprocess.run([sys.executable, '-m', 'spotdl', '--version'], 
                                  capture_output=True, 
                                  text=True, 
                                  timeout=5)
            if result.returncode == 0:
                print(f"✓ spotdl terdeteksi: {result.stdout.strip()}")
                return True
        except:
            pass
        
        return False

def rename_files_to_format(output_dir):
    """Rename file hasil download ke format: Artist - Title"""
    try:
        from mutagen.mp3 import MP3
        from mutagen.id3 import ID3
        
        renamed_count = 0
        for filename in os.listdir(output_dir):
            if filename.endswith('.mp3'):
                filepath = os.path.join(output_dir, filename)
                
                try:
                    # Baca metadata dari file
                    audio = MP3(filepath, ID3=ID3)
                    
                    # Ambil artist dan title dari metadata
                    artist = str(audio.get('TPE1', ['Unknown'])[0]) if 'TPE1' in audio else 'Unknown'
                    title = str(audio.get('TIT2', ['Unknown'])[0]) if 'TIT2' in audio else 'Unknown'
                    
                    # Format baru: Artist - Title.mp3
                    new_filename = f"{artist} - {title}.mp3"
                    
                    # Bersihkan karakter illegal untuk filename
                    illegal_chars = r'\/:*?"<>|'
                    for char in illegal_chars:
                        new_filename = new_filename.replace(char, '')
                    
                    new_filepath = os.path.join(output_dir, new_filename)
                    
                    # Rename jika nama berbeda
                    if filepath != new_filepath and not os.path.exists(new_filepath):
                        os.rename(filepath, new_filepath)
                        print(f"✓ Renamed: {new_filename}")
                        renamed_count += 1
                        
                except Exception as e:
                    print(f"⚠ Tidak bisa rename {filename}: {str(e)}")
        
        if renamed_count > 0:
            print(f"\n✓ {renamed_count} file berhasil di-rename ke format 'Artist - Title'")
                    
    except ImportError:
        print("\n⚠ mutagen tidak terinstall, file tidak di-rename")
        print("  Install dengan: pip install mutagen")

def download_with_spotdl(spotify_url, output_dir, cookies_txt=None):
    """Download menggunakan spotdl command line"""
    
    # Coba beberapa cara untuk menjalankan spotdl
    commands = [
        [sys.executable, '-m', 'spotdl'],  # Python module (lebih reliable)
        ['spotdl'],  # Direct command
    ]
    
    # Build arguments - TANPA --output-format karena tidak didukung di v4
    args = [
        spotify_url,
        '--output', output_dir,
        '--format', 'mp3',
    ]
    
    # Tambahkan cookies jika ada
    if cookies_txt and os.path.exists(cookies_txt):
        args.extend(['--cookie-file', cookies_txt])
    
    success = False
    for base_cmd in commands:
        cmd = base_cmd + args
        
        print(f"\n🎵 Menjalankan download...\n")
        
        try:
            # Jalankan spotdl
            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
                universal_newlines=True
            )
            
            # Print output real-time
            for line in process.stdout:
                print(line, end='')
            
            process.wait()
            
            if process.returncode == 0:
                print(f"\n✅ Download selesai! File disimpan di folder '{output_dir}'")
                
                # Rename file ke format yang diinginkan
                print("\n🔄 Mengubah nama file ke format 'Artist - Title'...")
                rename_files_to_format(output_dir)
                success = True
                break
            else:
                if base_cmd == commands[-1]:  # Last attempt
                    print(f"\n✗ Download gagal")
                else:
                    print(f"\n⚠ Mencoba cara lain...")
                continue
                
        except FileNotFoundError:
            if base_cmd == commands[-1]:
                print(f"✗ Command tidak ditemukan")
            else:
                continue
        except Exception as e:
            if base_cmd == commands[-1]:
                print(f"✗ Error: {str(e)}")
            else:
                continue
    
    if not success:
        print(f"\n✗ Download gagal. Coba jalankan manual: python -m spotdl {spotify_url}")
    
    return success

def download_spotify_track(spotify_url, output_dir="profile_music", cookie_file=None):
    """
    Download lagu dari Spotify menggunakan URL
    
    Args:
        spotify_url: URL track Spotify
        output_dir: Folder tujuan download
        cookie_file: Path ke file cookies dari Cookie Editor extension
    """
    
    # Buat folder output jika belum ada
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        print(f"✓ Folder '{output_dir}' dibuat")
    
    # Check apakah spotdl terinstall
    if not check_spotdl_installed():
        print("✗ spotdl tidak terinstall!")
        print("\nInstall dengan: pip install spotdl")
        return
    
    # Load dan konversi cookies jika ada
    cookies_txt = None
    if cookie_file and os.path.exists(cookie_file):
        cookies_dict = load_cookies(cookie_file)
        if cookies_dict:
            cookies_txt = "spotify_cookies_converted.txt"
            create_cookies_txt(cookies_dict, cookies_txt)
            print(f"✓ Cookies dikonversi ke format Netscape: {cookies_txt}\n")
    
    # Download menggunakan spotdl CLI
    success = download_with_spotdl(spotify_url, output_dir, cookies_txt)
    
    # Cleanup cookies file
    if cookies_txt and os.path.exists(cookies_txt):
        try:
            os.remove(cookies_txt)
        except:
            pass

def main():
    print("=" * 50)
    print("🎵  SPOTIFY DOWNLOADER")
    print("=" * 50)
    print()
    
    # Input URL Spotify
    spotify_url = input("Masukkan URL Spotify track/playlist: ").strip()
    
    if not spotify_url:
        print("✗ URL tidak boleh kosong!")
        return
    
    # Input folder output (opsional)
    output_dir = input("Folder tujuan (Enter = 'profile_music'): ").strip()
    if not output_dir:
        output_dir = "profile_music"
    
    # Input file cookies (default: spotify_cookies.json)
    use_cookies = input("Gunakan cookies? (y/n, default=y): ").strip().lower()
    cookie_file = None
    
    if use_cookies != 'n':
        cookie_path = input("Path cookies (Enter = 'spotify_cookies.json'): ").strip()
        cookie_file = cookie_path if cookie_path else "spotify_cookies.json"
        
        # Cek apakah file exists
        if not os.path.exists(cookie_file):
            print(f"⚠ File {cookie_file} tidak ditemukan, melanjutkan tanpa cookies...")
            cookie_file = None
    
    print()
    # Download
    download_spotify_track(spotify_url, output_dir, cookie_file)

if __name__ == "__main__":
    main()